### ISSUE TITLE
Using Hargreaves function to calculate PET for multiple sites

### ISSUE THREAD

**Issue by YvonneCollingham** [sbegueria/SPEI#13]
I am having a problem getting the SPEI Hargreaves function to calculate monthly PET for multiple sites. I pass minimum temperature and maximum temperature as matrices (12 months and 10 sites) and latitude as a vector with the same length as the number of sites. I am getting warning messages about longer object length not being a multiple of shorter object length (see below). Am I doing something wrong?
> dim(MinTest)
[1] 12 10
> dim(MaxTest)
[1] 12 10
> length(LatTest)
[1] 10
> har_test <- hargreaves(MinTest,MaxTest,Ra = NA,lat = LatTest)
Warning messages:
1: In -tan(latr) * tan(delta) :
  longer object length is not a multiple of shorter object length
2: In omegas * sin(latr) :
  longer object length is not a multiple of shorter object length
3: In cos(latr) * cos(delta) :
  longer object length is not a multiple of shorter object length

**Comment by Eromeroj** [comment]
I had the same issue, and I think the code is not handling matrices correctly. The problem was solved by modifying some lines of the script hargreaves.R. In line 198, instead of

`sset <- -tan(latr)*tan(delta)`

you can write the following loop:

`sset<-matrix(0,ncol=length(latr),nrow=length(delta))`
`for(i in 1:nrow(sset)){`
`  for(j in 1:ncol(sset)){`
`    sset[i,j]=-tan(latr[j])*tan(delta[i])`
`  }`
`}`

Additionally, line 204 should be changed. Instead of 

`Ra <- 37.6*dr*(omegas*sin(latr)*sin(delta)+cos(latr)*cos(delta)*sin(omegas))`

you can write

`Ra <- 37.6*dr*(t(t(omegas)*sin(latr))*sin(delta)+t(cos(latr)*t(cos(delta)*sin(omegas))))`

This way, the radiation is a matrix, where each column represents the time series of a spatial point.
Hope this helps.

**Comment by ash-pat** [comment]
Hi, @Eromeroj @YvonneCollingham 
Do you think the following warning message while using hargreaves is related to the above issue?

> Incompatible methods ("Ops.zoo", "Ops.ts") for "-"
>  Incompatible methods ("Ops.ts", "Ops.zoo") for "+"

I am also using a matrix with 3 sites. The code does finish simulating PET, but I am too much of a novice with R to know if the warning message should concern me.

**Comment by sbegueria** [comment]
Solved in new version (presumably 2.8, now in development branch).
