### ISSUE TITLE
Inf value

### ISSUE THREAD

**Issue by bkossakowskabanacka** [sbegueria/SPEI#69]
Hi 
Sometimes I get ”-Inf “ as SPEI result for months with the lowest climatic water balance (even when it’s not an outstanding value).  I know that "-Inf" stands for infinity (when dividing by zero) or the result that can’t be carried out at all. What is the reason I get that error calculating SPEI?  How can I debug it? I use the default  - log-Logistic distribution and ub-pwm method for parameter fitting.

I would be grateful for any help and tips regarding this topic. 

Barbara

**Comment by stranda** [comment]
My student and I are seeing the same thing.  Does anyone have a pointer on what's going on?
thanks much, allan

**Comment by sbegueria** [comment]
Hi, this is a known issue described on the papers, but still reappears from time to time. Not all data provide a good fit to the distribution, and some data combinations are simply impossible according to the model. It is not a bug in the code, but a mathematical limitation. It usually occurs at short time scales (e.g., one month), because as the accumulation period grows the data gets smoothed. Sometimes changing the distribution function helps, or the computation method, but there will always be some cases that do not fit. One could use an empirical distribution function, or a plotting position formula, for the cases that yield inifity, for instance, but this is not in the code since we preferred to abide to the 'canonical' methods.
